# Generated by Django 4.0.2 on 2022-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationrecord',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
